### ISSUE TITLE
Script can't seem to find oath entries?

### ISSUE THREAD

**Issue by Gowiem** [robertoriv/alfred-yubikey-otp#6]
Hey @robertoriv, was just going to build this myself and then saw you had already created. Love the idea, so thanks for building something off the shelf and open sourcing. I am running into an issue which I could use some guidance on: 

![image](https://user-images.githubusercontent.com/1392040/98017223-311d6800-1dbc-11eb-9ee9-a95876fb190a.png)

It seems your script can't find my oath entires. When I do a `ykman oath list` from my terminal, my single entry "oc" shows up, but your script isn't able to find it for some reason. Any suggestions on debugging that further?

**Comment by robertoriv** [comment]
Hi @Gowiem,

Sorry it took me a bit to get on this. Looking into it.

**Comment by robertoriv** [comment]
@Gowiem, 

Can you share the output of the following commands? (Please remove any identifying information.)

```
ykman oath info
ykman oath list
ykman oath code       # this is the command that gets executed when the workflow does the lookup
```

What I'm seeing in your logs is that the Yubikey is asking for you to touch it even before it returns a list of entries. That is not the behavior I see when I execute `ykman oath code` on any of my devices:

```
╰─ ykman oath code
Bitbucket                                  ######
Discord                                    ######
Dropbox                                    ######
Firefox                                    ######
GitHub                                     ######
GitHub(t)                      [Touch Credential]
...

╰─ ykman oath info
OATH version: 4.3.7
Password protection disabled
```

Tried it with both a **Yubikey 4** (USB-A) and a **Yubikey 5** (USB-C). Both behave the same:

I'm running **ykman** `3.1.1`:
```
╰─ ykman --version
YubiKey Manager (ykman) version: 3.1.1
Libraries:
    libykpers 1.20.0
    libusb 1.0.23
```

My logs:
```
...
23:48:35 workflow.py:2055 DEBUG    ---------- Yubikey OTP Codes Helper (1.0.0) ----------
23:48:35 workflow.py:1462 DEBUG    reading settings from /Users/rrivera/Library/Application Support/Alfred/Workflow Data/com.robertoriv.yubikey/settings.json
23:48:35 workflow.py:2339 DEBUG    update check not due
23:48:35 yubi.py:33 INFO     Bitbucket                                    ######
23:48:35 yubi.py:33 INFO     Discord                                      ######
23:48:35 yubi.py:33 INFO     Dropbox                                      ######
...
```

**Comment by Gowiem** [comment]
hey @robertoriv, thanks for getting back! Here's the info you asked for: 

```
~  » ykman oath info
OATH version: 5.2.7
Password protection disabled

~  » ykman oath list
oc
stuzobot

~  » ykman oath code
oc        [Touch Credential]
stuzobot  [Touch Credential]

~  » ykman --version
YubiKey Manager (ykman) version: 3.1.1
Libraries:
    libykpers 1.20.0
    libusb 1.0.23
```

I'm using a Yubikey 5 USB-C / NFC if that matters. 

At first glance, maybe this is a compatibility issue with the OATH version since you're using 4.3.7 and I'm on 5.2.7?

Let me know your thoughts or how I can help - Thanks!

**Comment by teimor** [comment]
I created a possible fix for oath 5.2.7 version in PR https://github.com/robertoriv/alfred-yubikey-otp/pull/8

**Comment by Gowiem** [comment]
@teimor awesome -- looking forward to seeing that merge, thanks!

**Comment by robertoriv** [comment]
@Gowiem I just released [v1.1.0](https://github.com/robertoriv/alfred-yubikey-otp/releases/tag/v1.1.0), which includes @teimor's fix, and a few additional changes.

The new version requires `ykman > v4.0.0` and was tested using an old Yubikey 4, and a 5c. Both worked just fine.

Give it a shot and let me know if it works for you.

**Comment by Gowiem** [comment]
Thanks @robertoriv -- Will check it out and report back my findings!

**Comment by Gowiem** [comment]
@robertoriv finding my various oath accounts is now working, so it seems that bug is fixed! Thanks @teimor!

It seems there is still an issue however, in that when I hit enter on a particular oath account, it will quickly prompt flash for the "Touch your yubikey..." and then it will revert back to the name of the account + "Require touch". If I hit enter at that point, the name of oath account is copied to my clipboard, but I never get an oath code. 

Any ideas on that one? Known thing or should I open up a new issue?

**Comment by robertoriv** [comment]
@Gowiem, I tried to reproduce the issue on a couple of devices (M1, Intel Macs) with no luck.

I've pushed a new version ([v1.1.1](https://github.com/robertoriv/alfred-yubikey-otp/releases/tag/v1.1.1)) with a couple of M1-specific fixes and more verbose logging. Try it out and, if you still have issues, add your Alfred logs. Here are mine, showing a successful run on an M1 Mac with a **Yubikey 4**:

```
[01:01:22.613] Yubikey OTP Codes Helper[Script Filter] Queuing argument ''
[01:01:23.397] Yubikey OTP Codes Helper[Script Filter] Script with argv '(null)' finished
[01:01:23.400] STDERR: Yubikey OTP Codes Helper[Script Filter] .
01:01:22 workflow.py:2061 DEBUG    ---------- Yubikey OTP Codes Helper (1.1.1) ----------
01:01:22 workflow.py:1468 DEBUG    reading settings from /Users/user/Library/Application Support/Alfred/Workflow Data/com.robertoriv.yubikey/settings.json
01:01:22 workflow.py:2343 DEBUG    update check not due
01:01:22 workflow.py:1695 DEBUG    loading cached data: /Users/user/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.robertoriv.yubikey/ykman_version.cpickle
01:01:22 yubi.py:27 DEBUG    Executing command: ['ykman', 'oath', 'accounts', 'code']
01:01:23 yubi.py:27 DEBUG    Executing command: ['ykman', 'oath', 'accounts', 'code']
01:01:23 yubi.py:42 DEBUG    Received: GitHub:robertoriv                                   ######
01:01:23 yubi.py:42 DEBUG    Received: GitHub(t):robertoriv                      [Requires Touch]
01:01:23 yubi.py:52 DEBUG    Code objects: [{'code': '######', 'name': 'GitHub:robertoriv'}, {'code': '[Requires Touch]']
01:01:23 workflow.py:1730 DEBUG    cached data: /Users/user/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.robertoriv.yubikey/ykman_available_codes.cpickle
01:01:23 yubi.py:164 DEBUG    Filtered: {'code': '######', 'name': 'GitHub:robertoriv'}
01:01:23 yubi.py:164 DEBUG    Filtered: {'code': '[Requires Touch]', 'name': 'GitHub(t):robertoriv'}
01:01:23 workflow.py:2254 DEBUG    set last run version: 1.1.1
01:01:23 workflow.py:2103 DEBUG    ---------- finished in 0.623s ----------
[01:01:23.405] Yubikey OTP Codes Helper[Script Filter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="yes"><title>GitHub:robertoriv</title><subtitle>Copy to ###### clipboard...</subtitle><arg>######</arg><icon>icons/github.png</icon></item><item valid="yes"><title>GitHub(t):robertoriv</title><subtitle>Require Touch</subtitle><arg>GitHub(t):robertoriv</arg><icon>icons/github.png</icon></item></items>
[01:01:25.598] Yubikey OTP Codes Helper[Script Filter] Queuing argument 'g'
[01:01:25.763] Yubikey OTP Codes Helper[Script Filter] Queuing argument 'gi'
[01:01:26.050] Yubikey OTP Codes Helper[Script Filter] Script with argv '(null)' finished
[01:01:26.059] STDERR: Yubikey OTP Codes Helper[Script Filter] .
01:01:25 workflow.py:2061 DEBUG    ---------- Yubikey OTP Codes Helper (1.1.1) ----------
01:01:25 workflow.py:1468 DEBUG    reading settings from /Users/user/Library/Application Support/Alfred/Workflow Data/com.robertoriv.yubikey/settings.json
01:01:25 workflow.py:2343 DEBUG    update check not due
01:01:25 workflow.py:1695 DEBUG    loading cached data: /Users/user/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.robertoriv.yubikey/ykman_version.cpickle
01:01:25 yubi.py:27 DEBUG    Executing command: ['ykman', 'oath', 'accounts', 'code']
01:01:25 workflow.py:1695 DEBUG    loading cached data: /Users/user/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.robertoriv.yubikey/ykman_available_codes.cpickle
01:01:25 yubi.py:164 DEBUG    Filtered: {'code': '######', 'name': 'GitHub:robertoriv'}
01:01:25 yubi.py:164 DEBUG    Filtered: {'code': '[Requires Touch]', 'name': 'GitHub(t):robertoriv'}
01:01:25 workflow.py:2254 DEBUG    set last run version: 1.1.1
01:01:25 workflow.py:2103 DEBUG    ---------- finished in 0.309s ----------
[01:01:26.062] Yubikey OTP Codes Helper[Script Filter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="yes"><title>GitHub:robertoriv</title><subtitle>Copy to ###### clipboard...</subtitle><arg>######</arg><icon>icons/github.png</icon></item><item valid="yes"><item valid="yes"><title>GitHub(t):robertoriv</title><subtitle>Require Touch</subtitle><arg>GitHub(t):robertoriv</arg><icon>icons/github.png</icon></item></items>
[01:01:26.299] Yubikey OTP Codes Helper[Script Filter] Queuing argument 'git'
[01:01:26.410] Yubikey OTP Codes Helper[Script Filter] Script with argv '(null)' finished
[01:01:26.423] STDERR: Yubikey OTP Codes Helper[Script Filter] .
01:01:26 workflow.py:2061 DEBUG    ---------- Yubikey OTP Codes Helper (1.1.1) ----------
01:01:26 workflow.py:1468 DEBUG    reading settings from /Users/user/Library/Application Support/Alfred/Workflow Data/com.robertoriv.yubikey/settings.json
01:01:26 workflow.py:2343 DEBUG    update check not due
01:01:26 workflow.py:1695 DEBUG    loading cached data: /Users/user/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.robertoriv.yubikey/ykman_version.cpickle
01:01:26 yubi.py:27 DEBUG    Executing command: ['ykman', 'oath', 'accounts', 'code']
01:01:26 workflow.py:1695 DEBUG    loading cached data: /Users/user/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.robertoriv.yubikey/ykman_available_codes.cpickle
01:01:26 yubi.py:164 DEBUG    Filtered: {'code': '######', 'name': 'GitHub:robertoriv'}
01:01:26 yubi.py:164 DEBUG    Filtered: {'code': '[Requires Touch]', 'name': 'GitHub(t):robertoriv'}
01:01:26 workflow.py:2254 DEBUG    set last run version: 1.1.1
01:01:26 workflow.py:2103 DEBUG    ---------- finished in 0.295s ----------
[01:01:26.425] Yubikey OTP Codes Helper[Script Filter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="yes"><title>GitHub:robertoriv</title><subtitle>Copy to ###### clipboard...</subtitle><arg>######</arg><icon>icons/github.png</icon></item><item valid="yes"><title>GitHub(t):robertoriv</title><subtitle>Require Touch</subtitle><arg>GitHub(t):robertoriv</arg><icon>icons/github.png</icon></item></items>
01:01:30 yubi.py:27 DEBUG    Executing command: ['ykman', 'oath', 'accounts', 'code']
01:01:30 workflow.py:1695 DEBUG    loading cached data: /Users/user/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.robertoriv.yubikey/ykman_available_codes.cpickle
01:01:30 yubi.py:164 DEBUG    Filtered: {'code': '[Requires Touch]', 'name': 'GitHub(t):robertoriv'}
Touch your YubiKey...
01:01:32 workflow.py:2254 DEBUG    set last run version: 1.1.1
01:01:32 workflow.py:2103 DEBUG    ---------- finished in 2.057s ----------
[01:01:32.740] Yubikey OTP Codes Helper[Script Filter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="yes"><title>GitHub(t):robertoriv</title><subtitle>Copy ###### to clipboard</subtitle><arg>######</arg><icon>icons/github.png</icon></item></items>
[01:01:33.209] Yubikey OTP Codes Helper[Script Filter] Processing complete
[01:01:33.211] Yubikey OTP Codes Helper[Script Filter] Passing output '######' to Copy to Clipboard
[01:01:33.216] Yubikey OTP Codes Helper[Copy to Clipboard] Processing complete
[01:01:33.216] Yubikey OTP Codes Helper[Copy to Clipboard] Passing output '######' to Play Sound
```

I also tried the workflow with a **Yubikey 5c** and found no issues.

**Comment by Gowiem** [comment]
@robertoriv ah good stuff -- Thanks man. I will follow up via a new issue if things are still wonky.

**Comment by Gowiem** [comment]
@robertoriv looks like all is good for this issue. Closing out. I opened up #9 for a new issue that I'm seeing, but overall it's working for a bunch of my oath entries except for my main one.
